<#
.SYNOPSIS
    幻想西游 Docker 一键部署（开发环境）
.DESCRIPTION
    1. 检查 config/config.php 是否存在 → 存在则引用，不存在则从 example 生成
    2. docker compose 构建并启动所有服务
.PARAMETER AppUrl
    站点访问地址，默认 http://localhost:8080
.PARAMETER AppPort
    宿主机映射端口，默认 8080
.PARAMETER MysqlPassword
    MySQL root 密码，默认 root
.PARAMETER NoBuild
    跳过镜像构建（适用于镜像未变化时快速重启）
.EXAMPLE
    .\docker_deploy.ps1
    .\docker_deploy.ps1 -AppUrl http://192.168.1.100:8080 -MysqlPassword mypass
#>

param(
    [string]$AppUrl   = "http://localhost:8080",
    [string]$AppPort  = "8080",
    [string]$MysqlPassword = "root",
    [switch]$NoBuild
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSCommandPath

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  幻想西游 · Docker 开发环境部署" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ──── 1. 检查依赖 ────
Write-Host "[检查] Docker 环境..." -ForegroundColor Yellow
try {
    docker version --format '{{.Server.Version}}' 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "Docker 未运行" }
    Write-Host "  Docker 已就绪" -ForegroundColor Green
} catch {
    Write-Host "  [错误] 请先启动 Docker Desktop" -ForegroundColor Red
    exit 1
}

# ──── 2. 配置文件处理 ────
Write-Host "[配置] 检查 config.php ..." -ForegroundColor Yellow

function New-ConfigFromExample {
    param([string]$ExamplePath, [string]$TargetPath, [string]$DbName)

    if (Test-Path $TargetPath) {
        Write-Host "  $TargetPath 已存在，使用现有配置" -ForegroundColor Green
        return
    }

    Write-Host "  从模板生成 $TargetPath ..." -ForegroundColor Gray
    $content = Get-Content $ExamplePath -Raw -Encoding UTF8

    # 替换 Docker 适配值
    $content = $content -replace "'localhost'", "'mysql'"
    $content = $content -replace "http://127\.0\.0\.1", $AppUrl
    $content = $content -replace "http://192\.168\.0\.21", $AppUrl   # 示例分区地址
    $content = $content -replace "debug']\s*=\s*false", "debug'] = true"
    $content = $content -replace "status']\s*=\s*0", "status'] = 1"  # 启用示例分区

    # 加入注释标记
    $header = "<?php `n// Auto-generated by docker_deploy.ps1 `n// 修改后不会被覆盖 `n`n"
    $content = $content -replace "^<\?php\s*", $header

    Set-Content $TargetPath -Value $content -Encoding UTF8 -NoNewline
    Write-Host "  已生成 $TargetPath" -ForegroundColor Green
}

# 先检查两个 config.php 是否都不存在，决定是否需要额外提示
$jyConfigExists  = Test-Path "$Root\config\config.php"
$xyConfigExists  = Test-Path "$Root\fqxy\config\config.php"

New-ConfigFromExample `
    -ExamplePath "$Root\config\config_example.php" `
    -TargetPath  "$Root\config\config.php" `
    -DbName "xxjyuser"

New-ConfigFromExample `
    -ExamplePath "$Root\fqxy\config\config_example.php" `
    -TargetPath  "$Root\fqxy\config\config.php" `
    -DbName "xyy"

# 如果是全新首次部署，提示 GM 账号
if (-not $jyConfigExists -and -not $xyConfigExists) {
    Write-Host ""
    Write-Host "  [提示] GM 账号需手动插入 xxjyuser.gmuser 表" -ForegroundColor DarkYellow
    Write-Host "  INSERT INTO gmuser (name,username,password) VALUES ('管理员','admin',md5('adminALL_PS'));" -ForegroundColor Gray
}

# ──── 3. 设置环境变量并启动 ────
Write-Host ""
Write-Host "[启动] Docker Compose ..." -ForegroundColor Yellow

$env:APP_PORT      = $AppPort
$env:MYSQL_PASSWORD = $MysqlPassword

$composeArgs = @(
    "compose",
    "-f", "$Root\docker\docker-compose.yml",
    "-p", "xiyou"
)

if ($NoBuild) {
    & docker @composeArgs up -d
} else {
    & docker @composeArgs up -d --build
}

if ($LASTEXITCODE -ne 0) {
    Write-Host "  [错误] 启动失败，请检查上方日志" -ForegroundColor Red
    exit 1
}

# ──── 4. 等待就绪 ────
Write-Host ""
Write-Host "[等待] 服务初始化（首次需下载镜像+导表，约 1~2 分钟）..." -ForegroundColor Yellow
Write-Host ""

docker @composeArgs logs -f --tail 5 app
